#!/bin/bash
TARGET=$1
git tag -l | sort -V -u -r | while read TAG ; do
  if [[ "$NEXT" == "$TARGET" ]] ; then 
    git log --oneline --decorate $TAG..$NEXT | while read COMMIT ; do
      echo $COMMIT
    done
    break
    fi
  NEXT=$TAG
done
FIRST=$(git tag -l | head -1)
if [[ "$FIRST" == "$TARGET" ]] ; then
  git log --oneline --decorate $FIRST | while read COMMIT ; do
      echo $COMMIT
    done
fi
