name: Release

on:
  push:
    tags:
      - v[0-9]+
permissions: write-all

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date)"
      - name: Get changelog
        id: changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git tag -l | sort -u -r | while read TAG ; do
              if [[ "$NEXT" == "$TARGET" ]] ; then 
                echo
                if [ $NEXT ] ; then
                  echo [$NEXT]
                else
                  echo "[Current]"
                fi
                echo "::set-output name=date::$(cat git log --no-merges --format=" * %s" $TAG..$NEXT)"
                  break
              fi
              NEXT=$TAG
            done
            FIRST=$(git tag -l | head -1)
            if [[ "$FIRST" == "$TARGET" ]] ; then
              echo
              echo [$FIRST]
              echo "::set-output name=date::$(cat git log --no-merges --format=" * %s" $FIRST)"
            fi
      - name: Create Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue create --title "RELEASE" --body "${{github.ref_name}} ${{ github.actor }} ${{ steps.date.outputs.date }} ${{steps.changelog.outputs.changelog}}"