name: Release

on:
  push:
    tags:
      - v[0-9]+
permissions: write-all

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue create --title "RELEASE" --body "${{github.ref_name}} ${{ github.actor }}"