name: Release

on:
  push:
    tags:
      - v[0-9]+
permissions: write-all

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date)"
      - name: Get changelog
        id: changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "changelog=$(./.github/scripts/changelog ${{github.ref_name}})" >> $GITHUB_OUTPUT
      - name: Create Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue create --title "RELEASE" --body "${{github.ref_name}} ${{ github.actor }} ${{ steps.date.outputs.date }} ${{steps.changelog.outputs.changelog}}"