name: Test

on:
  push:
permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: test
        run: git log --oneline --decorate | cat
